### ISSUE TITLE
Question: Do I have to copy two versions of every page? 

### ISSUE THREAD

**Issue by chug2k** [mccrodp/gatsby-starter-contentful-i18n#14]
I see that there's an `index.de.js` and `index.en-US.js` here. The only difference seems to be in the query associated with each file (as was the original).

Just wondering if there was a way to consolidate into one file and minimizing the need to copy/paste across two files.

**Comment by mccrodp** [comment]
Hey @chug2k, no, you don't need to create a new version of each page. I believe the starter that this one is built off uses the index static file as a way to route to something if you hit the top level domain. I'm sure there's a better way, you might be able to use a single index template for example and route from /pages/index.js to /templates/index.js and not need the additional language specific index page in /pages. But, for my case, I've only 2 languages, so 1 extra file wasn't an issue. Let me know if you figure that out and feel free to submit a PR.

Here's an example site I've built using this starter, the other content types in Contentful are just define as 1 single template, not lagnuages specific ones. Only index is language specific for the homepage. https://github.com/ahimsayogajp/ahimsayoga-gatsby/tree/master/src/templates
