### ISSUE TITLE
Investigate Converting TemplateWrapper to Component that extends React.Component

### ISSUE THREAD

**Issue by mccrodp** [mccrodp/gatsby-starter-contentful-i18n#3]
From Gatsby i18n plugin I've brought over the TemplateWrapper to this repo from [here](https://github.com/angeloocana/gatsby-plugin-i18n/blob/master/packages/gatsby-starter-default-i18n/src/layouts/index.js#L10).

Whereas the "Using Contentful" repo uses a React.Component as shown [here](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-contentful/src/layouts/index.js#L11).

I've used the TemplateWrapper from the i18n plugin as I need to pass those arguments for the i18n strings. There's probably a way I can do this with the Component method?

Also, this method has issue as it's designed to work with the static pages, not dynamic content from a CMS that uses templates, so in that way, our dynamic content: Products and Categories that use templates do not pass the i18n strings, so I need to do a hack for them here: https://github.com/mccrodp/gatsby-contentful-i18n/blob/master/src/layouts/index.js#L21

````js
if (i18nMessages === undefined) {
    if (langKey === 'de') {
      i18nMessages = messagesDe
    } else {
      i18nMessages = messagesEn
    }
  }
````

**Comment by romeboards** [comment]
Seeing the issue with dynamically created pages not getting the i18n strings - this seems like an issue where `gatsby-plugin-i18n` isn't applying the specialized layout (e.g. `src/layouts/en-US.js`) to a dynamically created path? 

Should that be something accounted for by the plugin, then?

**Comment by mccrodp** [comment]
Hey @romeboards, thanks a lot for chipping in here. Yes, I think you're right. I think it is related to what I mention on this issue on the plugin, but I don't know so much about it other than that at the moment. Would be great if you had anything to share on that, would love to address it. https://github.com/angeloocana/gatsby-plugin-i18n/issues/12#issuecomment-367591351 Cheers

**Comment by mccrodp** [comment]
Completed this for Gatsby v2 when adding a custom Layout component: https://github.com/mccrodp/gatsby-starter-contentful-i18n/commit/b861f8610a7cc3b1f92c0095f844f3ae522c81ee
