### ISSUE TITLE
Make the choice of language persistent across pages

### ISSUE THREAD

**Issue by tanvibhakta** [mccrodp/gatsby-starter-contentful-i18n#8]
## What is happening now
When I select 'de' the content on this page changes. However, when I navigate to a different oage via the link, my language setting isn't persistent, ie I have to select what language I want for every single page.

## What should happen
I should be able to select the language once and have this stay the same for me across teh entire website.

**Comment by mccrodp** [comment]
Hey, thanks for the issue. I haven't gotten a change to use this for a while. Actually, considering moving to use Strapi, so I might not update this repo any time soon, but PRs are welcome!

>when I navigate to a different oage via the link, my language setting isn't persistent
You need to make your nav links prefixed with the selected locale in your components, then it'll persist.

Pretend the links on the pages are the nav there and you'll see that they are calculated based on the chosen locale, just do that in your Menu component for example.
https://gatsby-starter-contentful-i18n.netlify.com/en-US/

**Comment by mccrodp** [comment]
@tanvibhakta, just upgraded this to Gatsby V2, so closing this now 😄
