### ISSUE TITLE
Add ui-string handling via contentful

### ISSUE THREAD

**Issue by tanvibhakta** [mccrodp/gatsby-starter-contentful-i18n#9]
I would love to see if it is possible to handle ui-strings translation via contenful as well, and if yes how to do so.

**Comment by mccrodp** [comment]
I doubt it, you'd need to create a new content type called "Strings" perhaps and new instance of it for every string you want to translate if you want to do that there, or just have 1 instance with an unlimited amount of "string" field instances in that content type and for each locale you'd be able to define what they are and just pull them into your site during Gatsby build and map them. If you don't need to edit them too often, best to just define them in a translations file. 

You could always store a translations field in a content type instance in Contentful either and pull that into Gatsby at build also??? Depends what you want. Best of luck with it!
